# Generated by Django 5.0.4 on 2024-05-26 18:17

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Publishing_a_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('departure', models.CharField(max_length=100, verbose_name='Отправление')),
                ('arrival', models.CharField(max_length=100, verbose_name='Прибытие')),
                ('models_auto', models.CharField(max_length=100, verbose_name='Модель автомобиля')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('seating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='Количество мест')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Опубликованные поездки',
                'verbose_name_plural': 'Опубликованные поездки',
            },
            managers=[
                ('car', django.db.models.manager.Manager()),
            ],
        ),
    ]
