# Generated by Django 5.0.4 on 2024-04-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0002_alter_category_name_alter_publishing_a_trip_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='names',
        ),
    ]
