# Generated by Django 5.0.4 on 2024-04-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0003_rename_name_category_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='names',
            new_name='name',
        ),
    ]
