# Generated by Django 5.0.4 on 2024-06-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0003_publishing_a_trip_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
