# Generated by Django 5.0.4 on 2024-04-14 18:36

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0004_rename_names_category_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publishing_a_trip',
            managers=[
                ('car', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='publishing_a_trip',
            name='price',
            field=models.CharField(default=1, max_length=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
