# Generated by Django 5.0.4 on 2024-06-28 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0005_alter_publishing_a_trip_arrival_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publishing_a_trip',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestcar.category', verbose_name='Категория'),
        ),
    ]
