# Generated by Django 5.0.4 on 2024-04-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0005_alter_publishing_a_trip_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='price',
            field=models.PositiveSmallIntegerField(max_length=10, verbose_name='Цена'),
        ),
    ]
