# Generated by Django 5.0.4 on 2024-06-30 22:22

import bestcar.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestcar', '0006_alter_publishing_a_trip_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='arrival',
            field=models.CharField(max_length=100, validators=[bestcar.validators.Validators_language_model()], verbose_name='прибытие'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='arrival_time',
            field=models.DateTimeField(default=None, validators=[bestcar.validators.Validators_date_model()], verbose_name='время прибытия'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bestcar.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='departure',
            field=models.CharField(max_length=100, validators=[bestcar.validators.Validators_language_model()], verbose_name='отправление'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='departure_time',
            field=models.DateTimeField(validators=[bestcar.validators.Validators_date_model()], verbose_name='время отправления'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='models_auto',
            field=models.CharField(max_length=100, verbose_name='модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='publishing_a_trip',
            name='seating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='количество мест'),
        ),
    ]
